### ISSUE TITLE
Remove page headers

### ISSUE THREAD

**Issue by ssvillarosa** [PUP-BSIT/project-lintrix#54]
Why do you have an entire new set of page in this files?
https://github.com/PUP-BSIT/project-lintrix/blob/d4e941ea96101516cff5c5413d29355b0cd80957/grademate/src/app/signup/signup.component.html#L1-L9

https://github.com/PUP-BSIT/project-lintrix/blob/d4e941ea96101516cff5c5413d29355b0cd80957/grademate/src/app/login/login.component.html#L1-L9

https://github.com/PUP-BSIT/project-lintrix/blob/d4e941ea96101516cff5c5413d29355b0cd80957/grademate/src/app/dashboard/dashboard.component.html#L1-L9

Remove this in all other files. It is already in your index.html file. Kindly update this file instead.
https://github.com/PUP-BSIT/project-lintrix/blob/d4e941ea96101516cff5c5413d29355b0cd80957/grademate/src/index.html#L1-L13

Also, practice modularization. That means you can break down your components into smaller components. That way, your code becomes cleaner and more maintainable.

**Comment by mingoedjudah** [comment]
This is is noted Sir Steven! We will do this as much as possible. Thank you very much for reviewing.

**Comment by alima-kailamarie** [comment]
Good afternoon, Sir Steven. I already remove the page headers in login, signup, and dashboard and it's already in pull requests. Also, we will practice modularization for our cleanliness of our codes. Thank you for your recommendation.
